name: Makefile CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install dependencies
      run: |
        if ! command -v make &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y make
        fi

    - name: Run Makefile
      run: make all
